=== Davidpsj/svgObjectModelGenerator/tests/schema/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "root",
	"description": "The root of the OMG document",
	"type": "object",
	"properties": {
		"artboards": {
			"type": "object",
			"description": "A map of artboard objects",
			"patternProperties": {
				"^[//W//w]+": {
					"description": "A artboard description",
					"type": "object",
					"properties": {
						"height": {
							"description": "The vertical dimension",
							"type": "number"
						},
						"meta": {
							"type": "object"
						},
						"name": {
							"description": "The user specified name of the artboard",
							"type": "string"
						},
						"width": {
							"description": "The horizontal dimension",
							"type": "number"
						},
						"x": {
							"description": "The horizontal position",
							"type": "number"
						},
						"y": {
							"description": "The vertical position",
							"type": "number"
						},
						"required": [ "x", "y", "width", "height" ]
					}
				}
			}
		},
		"backgroundLayer": { "$ref": "/color" },
		"children": {
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "/rect" },
					{ "$ref": "/circle" },
					{ "$ref": "/ellipse" },
					{ "$ref": "/line" },
					{ "$ref": "/path" },
					{ "$ref": "/polyline" },
					{ "$ref": "/polygon" },
					{ "$ref": "/text" },
					{ "$ref": "/image" },
					{ "$ref": "/reference" },
					{ "$ref": "/group" },
					{ "$ref": "/artboard" }
				]
			}
		},
		"desc": {
			"description": "The description of the document for accessibility purposes",
			"type": "string"
		},
		"meta": {
			"type": "object"
		},
		"multipleLayers": {
			"type": "boolean"
		},
		"name": {
			"description": "The user specified name of the document",
			"type": "string"
		},
		"colorMode": {
			"enum": [ "sRGB" ]
		},
		"rasterResolution": {
			"description": "The ratio between document pixels to an inch. In Photoshop this is `72` by default.",
			"type": "number",
			"minimum": 0
		},
		"resources": { "$ref": "/resources" },
		"viewSource": {
			"description": "The boundaries of the document in the application (PS/Ai).",
			"$ref": "/bounds"
		},
		"version": {
			"description": "The version of the OMG schema",
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [ "children", "version" ]
}

=== Davidpsj/svgObjectModelGenerator/tests/data/focal-point-on-radius-om.json
{
	"children": [
		{
			"id": "id_1",
			"transform": {
				"a": 1,
				"b": 0,
				"c": 0,
				"d": -1,
				"tx": 0,
				"ty": 560
			},
			"type": "group",
			"visualBounds": {
				"x": 7,
				"y": 496.7040100097656,
				"width": 161.33599853515625,
				"height": 63.295989990234375
			},
			"group": {
				"children": [
					{
						"id": "id_1_1",
						"style": {
							"clipPath": {
								"ref": "id_1_1_m"
							}
						},
						"type": "group",
						"visualBounds": {
							"x": 7,
							"y": 0,
							"width": 161.33599853515625,
							"height": 63.295997619628906
						},
						"group": {
							"children": [
								{
									"id": "id_1_1_1",
									"shape": {
										"path": "M7.000000,63.295998 L168.335999,63.295998 L168.335999,-0.000002 L7.000000,-0.000002 z",
										"type": "path"
									},
									"style": {
										"fill": {
											"gradient": {
												"ref": "grad_1",
												"cx": 0,
												"cy": 0,
												"fx": -1,
												"fy": 0.0006173209985718131,
												"r": 1,
												"transform": {
													"a": 61.285545349121094,
													"b": 0,
													"c": 0,
													"d": -61.285545349121094,
													"tx": 87.66798400878906,
													"ty": 31.602243423461914
												}
											},
											"type": "gradient"
										}
									},
									"type": "shape",
									"visualBounds": {
										"x": 7,
										"y": 0,
										"width": 161.33599853515625,
										"height": 63.295997619628906
									}
								}
							]
						}
					}
				]
			}
		}
	],
	"name": "rect.ai",
	"version": "1.0.0",
	"colorMode": "sRGB",
	"rasterResolution": 72,
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 960,
		"height": 560
	},
	"resources": {
		"clipPaths": {
			"id_1_1_m": {
				"children": [
					{
						"id": "id_1_1_m_shape",
						"shape": {
							"path": "M7.000000,31.603001 C7.000000,14.916000 39.820000,1.241000 81.483002,0.000000 L93.853996,0.000000 C135.516998,1.241000 168.335999,14.916000 168.335999,31.603001 C168.335999,49.106998 132.220001,63.296001 87.667999,63.296001 C43.116001,63.296001 7.000000,49.106998 7.000000,31.603001",
							"type": "path"
						},
						"type": "shape",
						"style": {
							"fill": {
								"type": "solid",
								"color": {
									"mode": "RGB",
									"value": {
										"r": 0,
										"g": 0,
										"b": 0
									},
									"alpha": 1
								}
							}
						}
					}
				],
				"type": "clipPath"
			}
		},
		"gradients": {
			"grad_1": {
				"stops": [
					{
						"color": {
							"mode": "RGB",
							"value": {
								"r": 0,
								"g": 0,
								"b": 255
							}
						},
						"offset": 0
					},
					{
						"color": {
							"mode": "RGB",
							"value": {
								"r": 0,
								"g": 0,
								"b": 255
							}
						},
						"offset": 0.13105900585651398
					},
					{
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 255,
								"b": 255
							}
						},
						"offset": 0.47108200192451477
					},
					{
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 147,
								"b": 29
							}
						},
						"offset": 1
					}
				],
				"type": "radial"
			}
		},
		"masks": {},
		"patterns": {},
		"styles": {}
	}
}

=== Davidpsj/svgObjectModelGenerator/tests/data/custom/tab-indentation-om.json
{
    "children": [
        {
            "type": "group",
            "name": "Layer 1",
            "group": {
                "children": [
                    {
                        "type": "shape",
                        "style": {
                            "fill": {
                                "type": "solid",
                                "color": {
                                    "mode": "RGB",
                                    "value": {
                                        "r": 0.0,
                                        "g": 161.0000056028366,
                                        "b": 75.00000312924385
                                    }
                                }
                            }
                        },
                        "visualBounds": {
                            "x": 0.0,
                            "y": 0.0,
                            "width": 99.99999998653039,
                            "height": 100.0
                        },
                        "shape": {
                            "type": "rect",
                            "x": 0.0,
                            "y": 0.0,
                            "width": 99.99999998653039,
                            "height": 100.0
                        }
                    }
                ]
            }
        }
    ],
    "name": "Untitled-2",
    "version": "1.0.0",
    "viewSource": {
        "x": 0.0,
        "y": 0.0,
        "width": 100.0,
        "height": 100.0
    },
    "resources": {}
}

=== Davidpsj/svgObjectModelGenerator/tests/data/svgGradient-radial-om.json
{
	"children": [
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "gradient",
					"gradient": {
						"units": "userSpaceOnUse",
						"r": 150,
						"cx": 450,
						"cy": 175,
						"ref": "radial-gradient"
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 300,
				"y": 100,
				"width": 300,
				"height": 150
			},
			"visualBounds": {
				"x": 300,
				"y": 100,
				"width": 300,
				"height": 150
			}
		},
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "gradient",
					"gradient": {
						"units": "userSpaceOnUse",
						"r": 500,
						"cx": 500,
						"cy": 375,
						"ref": "radial-gradient-2"
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 50,
				"y": 350,
				"width": 900,
				"height": 150
			},
			"visualBounds": {
				"x": 50,
				"y": 350,
				"width": 900,
				"height": 150
			}
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {
			"radial-gradient": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 41.003892,
								"g": 10,
								"b": 89.003893
							},
							"alpha": 1
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 124,
								"b": 0
							},
							"alpha": 1
						}
					}
				],
				"type": "radial"
			},
			"radial-gradient-2": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 41.003892,
								"g": 10,
								"b": 89.003893
							},
							"alpha": 1
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 124,
								"b": 0
							},
							"alpha": 1
						}
					}
				],
				"type": "radial"
			}
		},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 120,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"name": "svgGradient-radial.psd",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 1000,
		"height": 750
	},
	"rasterResolution": 144
}

=== Davidpsj/svgObjectModelGenerator/tests/data/positioned-text7-om.json
{
	"children": [
		{
			"group": {
				"children": [
					{
						"text": {
							"paragraphs": [
								{
									"lines": [
										[
											{
												"from": 0,
												"style": {
													"fill": {
														"color": {
															"value": {
																"b": 0,
																"g": 0,
																"r": 0
															},
															"mode": "RGB"
														},
														"type": "solid"
													},
													"font": {
														"family": "Myriad Pro",
														"size": 24,
														"style": "regular"
													},
													"textAttributes": {
														"letterSpacing": 96
													}
												},
												"to": 8
											}
										]
									],
									"style": {
										"font": {
											"size": 12
										}
									}
								}
							],
							"rawText": "Tracking",
							"frame": {
								"type": "positioned",
								"height": 26.0874,
								"path": "",
								"width": 853.727
							}
						},
						"transform": {
							"a": 1,
							"b": 0,
							"c": 0,
							"d": 1,
							"tx": 66.9976,
							"ty": 294.503
						},
						"type": "text",
						"visualBounds": {
							"height": 26.087,
							"x": 66.9736,
							"width": 853.7264,
							"y": 274.416
						}
					}
				]
			},
			"type": "group"
		}
	],
	"resources": {},
	"desc": "Created by Adobe Illustrator",
	"viewSource": {
		"height": 560,
		"x": 0,
		"width": 960,
		"y": 0
	},
	"name": "Tracking2",
	"version": "0.1.0"
}

=== Davidpsj/svgObjectModelGenerator/tests/data/svgGradient-om.json
{
	"children": [
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "gradient",
					"gradient": {
						"units": "userSpaceOnUse",
						"x1": 342.8888994943414,
						"y1": 250,
						"x2": 557.1111005056587,
						"y2": 100,
						"ref": "linear-gradient"
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 300,
				"y": 100,
				"width": 300,
				"height": 150
			},
			"visualBounds": {
				"x": 300,
				"y": 100,
				"width": 300,
				"height": 150
			}
		},
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "gradient",
					"gradient": {
						"units": "userSpaceOnUse",
						"x1": 0,
						"y1": 725.1037691048548,
						"x2": 1000,
						"y2": 24.896230895145152,
						"ref": "linear-gradient-2"
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 50,
				"y": 350,
				"width": 900,
				"height": 150
			},
			"visualBounds": {
				"x": 50,
				"y": 350,
				"width": 900,
				"height": 150
			}
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {
			"linear-gradient": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 41.003892,
								"g": 10,
								"b": 89.003893
							},
							"alpha": 1
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 124,
								"b": 0
							},
							"alpha": 1
						}
					}
				],
				"type": "linear"
			},
			"linear-gradient-2": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 41.003892,
								"g": 10,
								"b": 89.003893
							},
							"alpha": 1
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 124,
								"b": 0
							},
							"alpha": 1
						}
					}
				],
				"type": "linear"
			}
		},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 120,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"name": "svgGradient.psd",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 1000,
		"height": 750
	},
	"rasterResolution": 144
}

=== Davidpsj/svgObjectModelGenerator/tests/data/artboard-cropping/artboard-om.json
{
	"children": [
		{
			"type": "artboard",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				}
			},
			"name": "Artboard 1",
			"artboard": {
				"ref": "artboard-1",
				"children": [
					{
						"id": "shape-1",
						"type": "shape",
						"visible": true,
						"style": {
							"stroke": {
								"type": "none"
							},
							"fill": {
								"type": "gradient",
								"gradient": {
									"ref": "radial-gradient-1",
									"units": "userSpaceOnUse",
									"r": 100,
									"cx": 900,
									"cy": 900
								}
							}
						},
						"name": "Ellipse 1",
						"visualBounds": {
							"x": 800,
							"y": 800,
							"width": 200,
							"height": 200
						},
						"shape": {
							"type": "circle",
							"cx": 900,
							"cy": 900,
							"r": 100
						}
					},
					{
						"id": "shape-2",
						"type": "shape",
						"visible": true,
						"style": {
							"stroke": {
								"type": "none"
							},
							"fill": {
								"type": "gradient",
								"gradient": {
									"ref": "radial-gradient-2",
									"units": "userSpaceOnUse",
									"r": 100,
									"cx": 1300,
									"cy": 900
								}
							}
						},
						"name": "Ellipse 2",
						"visualBounds": {
							"x": 1200,
							"y": 800,
							"width": 200,
							"height": 200
						},
						"shape": {
							"type": "circle",
							"cx": 1300,
							"cy": 900,
							"r": 100
						}
					},
					{
						"id": "shape-3",
						"type": "shape",
						"visible": true,
						"style": {
							"stroke": {
								"type": "none"
							},
							"fill": {
								"type": "gradient",
								"gradient": {
									"ref": "radial-gradient-3",
									"units": "userSpaceOnUse",
									"r": 100,
									"cx": 900,
									"cy": 1300
								}
							}
						},
						"name": "Ellipse 3",
						"visualBounds": {
							"x": 800,
							"y": 1200,
							"width": 200,
							"height": 200
						},
						"shape": {
							"type": "circle",
							"cx": 900,
							"cy": 1300,
							"r": 100
						}
					},
					{
						"id": "shape-4",
						"type": "shape",
						"visible": true,
						"style": {
							"stroke": {
								"type": "none"
							},
							"fill": {
								"type": "gradient",
								"gradient": {
									"ref": "radial-gradient-4",
									"units": "userSpaceOnUse",
									"r": 100,
									"cx": 1300,
									"cy": 1300
								}
							}
						},
						"name": "Ellipse 4",
						"visualBounds": {
							"x": 1200,
							"y": 1200,
							"width": 200,
							"height": 200
						},
						"shape": {
							"type": "circle",
							"cx": 1300,
							"cy": 1300,
							"r": 100
						}
					}
				]
			}
		}
	],
	"artboards": {
		"artboard-1": {
			"name": "Artboard 1",
			"x": 900,
			"y": 900,
			"width": 400,
			"height": 400
		}
	},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 90,
				"altitude": 30
			}
		}
	},
	"name": "artboard-cropping.psd",
	"rasterResolution": 72,
	"version": "1.5.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 2200,
		"height": 2200
	},
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {
			"radial-gradient-1": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 9.57588,
								"g": 0.00389105,
								"b": 178
							},
							"alpha": 1
						}
					},
					{
						"offset": 0.5,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 0.00389105,
								"b": 0.0272374
							}
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 251.996,
								"b": 0.00389105
							},
							"alpha": 1
						}
					}
				],
				"type": "radial"
			},
			"radial-gradient-2": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 9.57588,
								"g": 0.00389105,
								"b": 178
							},
							"alpha": 1
						}
					},
					{
						"offset": 0.5,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 0.00389105,
								"b": 0.0272374
							}
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 251.996,
								"b": 0.00389105
							},
							"alpha": 1
						}
					}
				],
				"type": "radial"
			},
			"radial-gradient-3": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 9.57588,
								"g": 0.00389105,
								"b": 178
							},
							"alpha": 1
						}
					},
					{
						"offset": 0.5,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 0.00389105,
								"b": 0.0272374
							}
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 251.996,
								"b": 0.00389105
							},
							"alpha": 1
						}
					}
				],
				"type": "radial"
			},
			"radial-gradient-4": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 9.57588,
								"g": 0.00389105,
								"b": 178
							},
							"alpha": 1
						}
					},
					{
						"offset": 0.5,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 0.00389105,
								"b": 0.0272374
							}
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 251.996,
								"b": 0.00389105
							},
							"alpha": 1
						}
					}
				],
				"type": "radial"
			}
		},
		"masks": {},
		"patterns": {}
	}
}

=== Davidpsj/svgObjectModelGenerator/tests/data/artboards-2/artboards-2-9-om.json
{
	"children": [
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 255,
							"b": 0
						},
						"alpha": 1
					}
				}
			},
			"shape": {
				"type": "circle",
				"cx": 2512,
				"cy": 2512,
				"r": 387
			},
			"visualBounds": {
				"x": 2125,
				"y": 2125,
				"width": 774,
				"height": 774
			}
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 90,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 5024,
		"height": 5024
	},
	"rasterResolution": 326
}

=== Davidpsj/svgObjectModelGenerator/tests/data/artboard-cropping/ellipse-2-om.json
{
	"children": [
		{
			"id": "shape-1",
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "gradient",
					"gradient": {
						"ref": "radial-gradient-1",
						"units": "userSpaceOnUse",
						"r": 100,
						"cx": 1300,
						"cy": 900
					}
				}
			},
			"name": "Ellipse 2",
			"visualBounds": {
				"x": 1200,
				"y": 800,
				"width": 200,
				"height": 200
			},
			"shape": {
				"type": "circle",
				"cx": 1300,
				"cy": 900,
				"r": 100
			}
		}
	],
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 90,
				"altitude": 30
			}
		}
	},
	"rasterResolution": 72,
	"name": "artboard-cropping.psd",
	"version": "1.5.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 2200,
		"height": 2200
	},
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {
			"radial-gradient-1": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 9.57588,
								"g": 0.00389105,
								"b": 178
							},
							"alpha": 1
						}
					},
					{
						"offset": 0.5,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 0.00389105,
								"b": 0.0272374
							}
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 251.996,
								"b": 0.00389105
							},
							"alpha": 1
						}
					}
				],
				"type": "radial"
			}
		},
		"masks": {},
		"patterns": {}
	}
}
