=== Davidpsj/svgObjectModelGenerator/tests/schema/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "root",
	"description": "The root of the OMG document",
	"type": "object",
	"properties": {
		"artboards": {
			"type": "object",
			"description": "A map of artboard objects",
			"patternProperties": {
				"^[//W//w]+": {
					"description": "A artboard description",
					"type": "object",
					"properties": {
						"height": {
							"description": "The vertical dimension",
							"type": "number"
						},
						"meta": {
							"type": "object"
						},
						"name": {
							"description": "The user specified name of the artboard",
							"type": "string"
						},
						"width": {
							"description": "The horizontal dimension",
							"type": "number"
						},
						"x": {
							"description": "The horizontal position",
							"type": "number"
						},
						"y": {
							"description": "The vertical position",
							"type": "number"
						},
						"required": [ "x", "y", "width", "height" ]
					}
				}
			}
		},
		"backgroundLayer": { "$ref": "/color" },
		"children": {
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "/rect" },
					{ "$ref": "/circle" },
					{ "$ref": "/ellipse" },
					{ "$ref": "/line" },
					{ "$ref": "/path" },
					{ "$ref": "/polyline" },
					{ "$ref": "/polygon" },
					{ "$ref": "/text" },
					{ "$ref": "/image" },
					{ "$ref": "/reference" },
					{ "$ref": "/group" },
					{ "$ref": "/artboard" }
				]
			}
		},
		"desc": {
			"description": "The description of the document for accessibility purposes",
			"type": "string"
		},
		"meta": {
			"type": "object"
		},
		"multipleLayers": {
			"type": "boolean"
		},
		"name": {
			"description": "The user specified name of the document",
			"type": "string"
		},
		"colorMode": {
			"enum": [ "sRGB" ]
		},
		"rasterResolution": {
			"description": "The ratio between document pixels to an inch. In Photoshop this is `72` by default.",
			"type": "number",
			"minimum": 0
		},
		"resources": { "$ref": "/resources" },
		"viewSource": {
			"description": "The boundaries of the document in the application (PS/Ai).",
			"$ref": "/bounds"
		},
		"version": {
			"description": "The version of the OMG schema",
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [ "children", "version" ]
}

=== Davidpsj/svgObjectModelGenerator/tests/data/radial-gradient-angle-global/radial-gradient-angle-global-11-om.json
{
	"children": [
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "gradient",
					"gradient": {
						"units": "userSpaceOnUse",
						"r": 300,
						"cx": 400,
						"cy": 300,
						"ref": "radial-gradient"
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 50,
				"y": 500,
				"width": 200,
				"height": 100
			},
			"visualBounds": {
				"x": 50,
				"y": 500,
				"width": 200,
				"height": 100
			}
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {
			"radial-gradient": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 0.003891,
								"b": 0.003891
							},
							"alpha": 1
						}
					},
					{
						"offset": 0.14990234375,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 0,
								"b": 255
							}
						}
					},
					{
						"offset": 0.330078125,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 0,
								"g": 0,
								"b": 255
							}
						}
					},
					{
						"offset": 0.489990234375,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 0,
								"g": 255,
								"b": 255
							}
						}
					},
					{
						"offset": 0.669921875,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 0,
								"g": 255,
								"b": 0
							}
						}
					},
					{
						"offset": 0.840087890625,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 255,
								"b": 0
							}
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 255,
								"g": 0.003891,
								"b": 0.003891
							},
							"alpha": 1
						}
					}
				],
				"type": "radial"
			}
		},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 120,
				"altitude": 30
			}
		}
	},
	"version": "1.5.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 800,
		"height": 600
	},
	"rasterResolution": 72
}

=== Davidpsj/svgObjectModelGenerator/tests/data/svgText-writing-mode-om.json
{
	"children": [
		{
			"type": "text",
			"visible": true,
			"style": {
				"writing-mode": "tb",
				"glyph-orientation-vertical": "0",
				"font-size": 63.6352,
				"stroke": {
					"type": "none"
				}
			},
			"name": "This is a text",
			"visualBounds": {
				"x": 321,
				"y": 241,
				"width": 36,
				"height": 724
			},
			"position": {
				"x": 338.33593856,
				"y": 231.55468288,
				"unitX": "px",
				"unitY": "px"
			},
			"maxTextSize": 63.6352,
			"children": [
				{
					"type": "tspan",
					"visible": true,
					"style": {
						"font-size": 63.6352,
						"fill": {
							"type": "solid",
							"color": {
								"mode": "RGB",
								"value": {
									"r": 3,
									"g": 3,
									"b": 3
								},
								"alpha": 1
							}
						},
						"font-family": "\"Minion Pro\""
					},
					"text": "This is a text",
					"visualBounds": {
						"x": 321,
						"y": 241,
						"width": 36,
						"height": 724
					},
					"position": {
						"x": 338.33593856,
						"y": 0,
						"unitX": "px",
						"unitY": "em"
					}
				}
			]
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 120,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"name": "svgText-writing-mode",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 1024,
		"height": 1024
	},
	"rasterResolution": 144
}

=== Davidpsj/svgObjectModelGenerator/tests/data/text-transform-om.json
{
	"children": [
		{
			"type": "text",
			"visible": true,
			"style": {
				"font-size": 30,
				"stroke": {
					"type": "none"
				}
			},
			"name": "Text.svg",
			"visualBounds": {
				"x": 232,
				"y": 314,
				"width": 54,
				"height": 47
			},
			"position": {
				"x": 0,
				"y": 0,
				"unitY": "px",
				"unitX": "px"
			},
			"maxTextSize": 30,
			"transform": {
				"a": 0.707107,
				"b": -0.707107,
				"c": 0.707107,
				"d": 0.707107,
				"tx": 0,
				"ty": 0
			},
			"transformTX": 246.896664,
			"transformTY": 366.186822,
			"children": [
				{
					"type": "tspan",
					"visible": true,
					"style": {
						"font-size": 30,
						"font-family": "Arial"
					},
					"text": "Text",
					"visualBounds": {
						"x": 232,
						"y": 314,
						"width": 54,
						"height": 47
					},
					"position": {
						"x": 0,
						"y": 0,
						"unitX": "px",
						"unitY": "em"
					}
				}
			]
		},
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "solid",
					"align": "inside",
					"cap": "butt",
					"join": "miter",
					"width": 3,
					"miterLimit": 100,
					"dash": [],
					"dashOffset": 0,
					"color": {
						"mode": "RGB",
						"value": {
							"r": 241.881842,
							"g": 101.179413,
							"b": 33.72992
						},
						"alpha": 1
					},
					"opacity": 1
				}
			},
			"shape": {
				"type": "rect",
				"x": 208,
				"y": 275,
				"width": 98,
				"height": 121
			},
			"visualBounds": {
				"x": 208,
				"y": 275,
				"width": 98,
				"height": 121
			}
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 120,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"name": "text-transform.psd",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 800,
		"height": 600
	},
	"rasterResolution": 72
}

=== Davidpsj/svgObjectModelGenerator/tests/data/text-on-path-2/text-on-path-2-9-om.json
{
	"children": [
		{
			"type": "text",
			"visible": true,
			"style": {
				"font-size": 150,
				"stroke": {
					"type": "none"
				}
			},
			"name": "more path text.svg",
			"visualBounds": {
				"x": -82.19421249999999,
				"y": -80.8879375,
				"width": 598.6046125,
				"height": 476.00329583333337
			},
			"position": {
				"x": 0,
				"y": 0
			},
			"children": [
				{
					"type": "textPath",
					"visible": true,
					"style": {
						"text-anchor": "end",
						"font-size": 150
					},
					"pathData": "M 360.72 269.76 C 390.941 269.76 415.44 284.803 415.44 303.36 C 415.44 321.917 390.941 336.96 360.72 336.96 C 330.499 336.96 306 321.917 306 303.36 Z",
					"children": [
						{
							"type": "tspan",
							"visible": true,
							"style": {
								"text-anchor": "end",
								"font-size": 150,
								"fill": {
									"type": "solid",
									"color": {
										"mode": "RGB",
										"value": {
											"r": 34.412245,
											"g": 107.000556,
											"b": 37.821601
										},
										"alpha": 1
									}
								},
								"font-family": "Optima",
								"font-weight": 900
							},
							"text": "more path text ",
							"visualBounds": {
								"x": 1192,
								"y": 1042,
								"width": 600,
								"height": 478
							},
							"position": {
								"x": 0,
								"y": 0,
								"unitX": "px",
								"unitY": "em"
							}
						}
					]
				}
			],
			"maxTextSize": 150
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 90,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"name": "text-on-path-2.psd",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 2100,
		"height": 1500
	},
	"rasterResolution": 300
}

=== Davidpsj/svgObjectModelGenerator/tests/data/clipPath/clipPath-1-om.json
{
	"children": [
		{
			"id": "shape-1",
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "solid",
					"cap": "butt",
					"join": "miter",
					"width": 14,
					"miterLimit": 100,
					"dash": [],
					"dashOffset": 0,
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 0.091882,
							"b": 0.102416
						},
						"alpha": 1
					},
					"opacity": 1
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 113.686632,
							"b": 187.776986
						},
						"alpha": 1
					}
				}
			},
			"name": "Rectangle 1",
			"visualBounds": {
				"x": 130,
				"y": 66,
				"width": 179,
				"height": 179
			},
			"shape": {
				"type": "rect",
				"x": 130,
				"y": 66,
				"width": 179,
				"height": 179
			}
		},
		{
			"id": "shape-2",
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none",
					"cap": "butt",
					"join": "miter",
					"width": 3,
					"miterLimit": 100,
					"dash": [],
					"dashOffset": 0,
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 0.091882,
							"b": 0.102416
						},
						"alpha": 1
					},
					"opacity": 1
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 237.272538,
							"g": 28.469096,
							"b": 36.259087
						},
						"alpha": 1
					}
				},
				"clipPath": {
					"ref": "clipPath1"
				}
			},
			"name": "Ellipse 1",
			"visualBounds": {
				"x": 215,
				"y": 151,
				"width": 188,
				"height": 188
			},
			"shape": {
				"type": "circle",
				"cx": 309,
				"cy": 245,
				"r": 94
			}
		}
	],
	"artboards": {},
	"meta": {},
	"name": "ClipPath test",
	"rasterResolution": 72,
	"version": "1.5.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 1024,
		"height": 768
	},
	"resources": {
		"clipPaths": {
			"clipPath1": {
				"children": [
					{
						"id": "shape-3",
						"type": "shape",
						"visible": true,
						"style": {
							"stroke": {
								"type": "solid",
								"cap": "butt",
								"join": "miter",
								"width": 14,
								"miterLimit": 100,
								"dash": [],
								"dashOffset": 0,
								"color": {
									"mode": "RGB",
									"value": {
										"r": 0,
										"g": 0.091882,
										"b": 0.102416
									},
									"alpha": 1
								},
								"opacity": 1
							},
							"fill": {
								"type": "solid",
								"color": {
									"mode": "RGB",
									"value": {
										"r": 0,
										"g": 113.686632,
										"b": 187.776986
									},
									"alpha": 1
								}
							}
						},
						"name": "Rectangle 1",
						"visualBounds": {
							"x": 130,
							"y": 67,
							"width": 179,
							"height": 178
						},
						"shape": {
							"type": "rect",
							"x": 130,
							"y": 67,
							"width": 179,
							"height": 179
						}
					}
				],
				"type": "clipPath"
			}
		},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	}
}

=== Davidpsj/svgObjectModelGenerator/tests/data/svgRect-om.json
{
	"children": [
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 62.809338,
							"g": 144.252921,
							"b": 182.000004
						},
						"alpha": 1
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 70,
				"y": 100,
				"width": 338,
				"height": 163
			},
			"visualBounds": {
				"x": 70,
				"y": 100,
				"width": 338,
				"height": 163
			}
		},
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 62.809338,
							"g": 144.252921,
							"b": 182.000004
						},
						"alpha": 1
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 500,
				"y": 100,
				"width": 300,
				"height": 150,
				"r": [
					30,
					30,
					30,
					30
				]
			},
			"visualBounds": {
				"x": 500,
				"y": 100,
				"width": 300,
				"height": 150
			}
		},
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 62.809338,
							"g": 144.252921,
							"b": 182.000004
						},
						"alpha": 1
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 70,
				"y": 300,
				"width": 300,
				"height": 150,
				"r": [
					40,
					10,
					20,
					30
				]
			},
			"visualBounds": {
				"x": 70,
				"y": 300,
				"width": 300,
				"height": 150
			}
		},
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 62.809338,
							"g": 144.252921,
							"b": 182.000004
						},
						"alpha": 1
					}
				}
			},
			"shape": {
				"type": "rect",
				"x": 380,
				"y": 300,
				"width": 300,
				"height": 150,
				"r": [
					20,
					10,
					200,
					150
				]
			},
			"visualBounds": {
				"x": 380,
				"y": 300,
				"width": 300,
				"height": 150
			}
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 120,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"name": "rect.psd",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 1024,
		"height": 1024
	},
	"rasterResolution": 144
}

=== Davidpsj/svgObjectModelGenerator/tests/data/clipPath/clipPath-7-om.json
{
	"children": [
		{
			"id": "shape-1",
			"type": "shape",
			"visible": true,
			"style": {
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 127,
							"b": 0
						},
						"alpha": 1
					}
				},
				"clipPath": {
					"ref": "clipPath1"
				}
			},
			"name": "Rectangle 1",
			"visualBounds": {
				"x": 0,
				"y": 0,
				"width": 300,
				"height": 300
			},
			"shape": {
				"type": "rect",
				"x": 0,
				"y": 0,
				"width": 300,
				"height": 300
			}
		}
	],
	"artboards": {},
	"meta": {},
	"name": "ClipPath test",
	"rasterResolution": 72,
	"version": "1.0.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 1024,
		"height": 768
	},
	"resources": {
		"clipPaths": {
			"clipPath1": {
				"children": [
					{
						"id": "shape-2",
						"type": "shape",
						"visible": true,
						"name": "Rectangle 1",
						"visualBounds": {
							"x": 50,
							"y": 50,
							"width": 200,
							"height": 200
						},
						"style": {
							"clipPath": {
								"ref": "clipPath2"
							}
						},
						"shape": {
							"type": "path",
							"path": "M50,50 L250,50 L250,250 L50,250z",
							"winding": "evenodd"
						}
					}
				],
				"type": "clipPath"
			},
			"clipPath2": {
				"children": [
					{
						"id": "shape-3",
						"type": "shape",
						"visible": true,
						"name": "Rectangle 1",
						"visualBounds": {
							"x": 100,
							"y": 100,
							"width": 100,
							"height": 100
						},
						"shape": {
							"type": "path",
							"path": "M100,100 L200,100 L200,200 L100,200z",
							"winding": "evenodd"
						}
					}
				],
				"type": "clipPath"
			}
		},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	}
}

=== Davidpsj/svgObjectModelGenerator/tests/data/group-transform-om.json
{
	"children": [
		{
			"id": "id_1",
			"transform": {
				"a": 1,
				"b": 0,
				"c": 0,
				"d": -1,
				"tx": 0,
				"ty": 560
			},
			"type": "group",
			"visualBounds": {
				"x": 0,
				"y": 0,
				"width": 121,
				"height": 92
			},
			"group": {
				"children": [
					{
						"id": "id_1_1",
						"shape": {
							"path": "M0.000000,468.000000 L121.000000,468.000000 L121.000000,560.000000 L0.000000,560.000000 z",
							"type": "path"
						},
						"style": {
							"fill": {
								"color": {
									"mode": "RGB",
									"value": {
										"r": 0,
										"g": 255,
										"b": 0
									},
									"alpha": 1
								},
								"type": "solid"
							}
						},
						"type": "shape",
						"visualBounds": {
							"x": 0,
							"y": 468,
							"width": 121,
							"height": 92
						}
					}
				]
			}
		}
	],
	"name": "Group transform",
	"rasterResolution": 72,
	"version": "1.0.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 960,
		"height": 560
	},
	"colorMode": "sRGB",
	"resources": {
		"gradients": {},
		"masks": {},
		"patterns": {},
		"styles": {}
	}
}
