=== Davidpsj/svgObjectModelGenerator/tests/schema/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "root",
	"description": "The root of the OMG document",
	"type": "object",
	"properties": {
		"artboards": {
			"type": "object",
			"description": "A map of artboard objects",
			"patternProperties": {
				"^[//W//w]+": {
					"description": "A artboard description",
					"type": "object",
					"properties": {
						"height": {
							"description": "The vertical dimension",
							"type": "number"
						},
						"meta": {
							"type": "object"
						},
						"name": {
							"description": "The user specified name of the artboard",
							"type": "string"
						},
						"width": {
							"description": "The horizontal dimension",
							"type": "number"
						},
						"x": {
							"description": "The horizontal position",
							"type": "number"
						},
						"y": {
							"description": "The vertical position",
							"type": "number"
						},
						"required": [ "x", "y", "width", "height" ]
					}
				}
			}
		},
		"backgroundLayer": { "$ref": "/color" },
		"children": {
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "/rect" },
					{ "$ref": "/circle" },
					{ "$ref": "/ellipse" },
					{ "$ref": "/line" },
					{ "$ref": "/path" },
					{ "$ref": "/polyline" },
					{ "$ref": "/polygon" },
					{ "$ref": "/text" },
					{ "$ref": "/image" },
					{ "$ref": "/reference" },
					{ "$ref": "/group" },
					{ "$ref": "/artboard" }
				]
			}
		},
		"desc": {
			"description": "The description of the document for accessibility purposes",
			"type": "string"
		},
		"meta": {
			"type": "object"
		},
		"multipleLayers": {
			"type": "boolean"
		},
		"name": {
			"description": "The user specified name of the document",
			"type": "string"
		},
		"colorMode": {
			"enum": [ "sRGB" ]
		},
		"rasterResolution": {
			"description": "The ratio between document pixels to an inch. In Photoshop this is `72` by default.",
			"type": "number",
			"minimum": 0
		},
		"resources": { "$ref": "/resources" },
		"viewSource": {
			"description": "The boundaries of the document in the application (PS/Ai).",
			"$ref": "/bounds"
		},
		"version": {
			"description": "The version of the OMG schema",
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [ "children", "version" ]
}

=== Davidpsj/svgObjectModelGenerator/tests/data/custom/empty-group-2-om.json
{
	"children": [
		{
			"type": "group",
			"group": {
				"children": [
					{
						"name": "Button_over",
						"type": "group",
						"group": {
							"children": [
								{
									"name": "Home",
									"type": "group",
									"group": {
										"children": []
									}
								}
							]
						}
					},
					{
						"name": "Button_over2",
						"type": "group",
						"group": {
							"children": [
								{
									"name": "Home2",
									"type": "group",
									"group": {
										"children": []
									}
								}
							]
						}
					}
				]
			}
		}
	],
	"desc": "Created by Adobe Illustrator",
	"name": "ExpandDeletedSymbol2",
	"version": "1.5.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 960,
		"height": 560
	},
	"resources": {}
}

=== Davidpsj/svgObjectModelGenerator/tests/data/artboards-1/artboards-1-2-om.json
{
	"children": [
		{
			"type": "artboard",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				}
			},
			"artboard": {
				"ref": "artboard",
				"children": [
					{
						"type": "shape",
						"visible": true,
						"style": {
							"stroke": {
								"type": "none"
							},
							"fill": {
								"type": "solid",
								"color": {
									"mode": "RGB",
									"value": {
										"r": 0,
										"g": 255,
										"b": 0
									},
									"alpha": 1
								}
							}
						},
						"shape": {
							"type": "circle",
							"cx": 2540,
							"cy": 2960,
							"r": 393
						},
						"visualBounds": {
							"x": 2147,
							"y": 2567,
							"width": 786,
							"height": 786
						}
					}
				]
			},
			"name": "square"
		},
		{
			"type": "artboard",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				}
			},
			"artboard": {
				"ref": "artboard-2",
				"children": [
					{
						"type": "shape",
						"visible": true,
						"style": {
							"stroke": {
								"type": "none"
							},
							"fill": {
								"type": "solid",
								"color": {
									"mode": "RGB",
									"value": {
										"r": 0,
										"g": 255,
										"b": 0
									},
									"alpha": 1
								}
							}
						},
						"shape": {
							"type": "rect",
							"x": 3972,
							"y": 2811,
							"width": 533,
							"height": 533
						},
						"visualBounds": {
							"x": 3972,
							"y": 2811,
							"width": 533,
							"height": 533
						}
					}
				]
			},
			"name": "iPhone"
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"artboards": {
		"artboard": {
			"name": "square",
			"x": 2000,
			"y": 2000,
			"width": 1080,
			"height": 1920
		},
		"artboard-2": {
			"name": "iPhone",
			"x": 3658,
			"y": 2497,
			"width": 1162,
			"height": 1162
		}
	},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 90,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 5080,
		"height": 5920
	},
	"rasterResolution": 326
}

=== Davidpsj/svgObjectModelGenerator/tests/data/pixelImage/pixelImage-1-om.json
{
	"children": [],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 120,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"name": "pixelImage.psd",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 100,
		"height": 100
	},
	"rasterResolution": 72
}

=== Davidpsj/svgObjectModelGenerator/tests/data/clipPath/clipPath-shift-om.json
{
	"children": [
		{
			"type": "shape",
			"style": {
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 0,
							"b": 127
						},
						"alpha": 0.5
					}
				},
				"clipPath": {
					"ref": "clipPath1"
				}
			},
			"visualBounds": {
				"x": 50,
				"y": 50,
				"width": 150,
				"height": 150
			},
			"shape": {
				"type": "rect",
				"x": 50,
				"y": 50,
				"width": 100,
				"height": 100
			}
		},
		{
			"type": "shape",
			"style": {
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 127,
							"b": 0
						},
						"alpha": 0.5
					}
				},
				"clipPath": {
					"ref": "clipPath1"
				}
			},
			"visualBounds": {
				"x": 50,
				"y": 50,
				"width": 150,
				"height": 150
			},
			"shape": {
				"type": "path",
				"path": "M50,50 L150,50 L150,150 L50,150 z"
			}
		}
	],
	"artboards": {},
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 1024,
		"height": 768
	},
	"version": "1.0.0",
	"resources": {
		"masks": {},
		"filters": {},
		"gradients": {},
		"clipPaths": {
			"clipPath1": {
				"children": [
					{
						"type": "shape",
						"visualBounds": {
							"x": 50,
							"y": 50,
							"width": 100,
							"height": 100
						},
						"shape": {
							"type": "circle",
							"cx": 100,
							"cy": 100,
							"r": 50
						}
					}
				],
				"type": "clipPath"
			}
		},
		"patterns": {}
	}
}

=== Davidpsj/svgObjectModelGenerator/tests/data/svgFx-inner-glow-om.json
{
	"children": [
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 252.970012,
							"g": 197.757364,
							"b": 137.454736
						},
						"alpha": 1
					}
				},
				"meta": {
					"PS": {
						"fx": {
							"innerGlowMulti": [
								{
									"enabled": true,
									"mode": "lighten",
									"gradient": {
										"stops": [
											{
												"offset": 0,
												"color": {
													"mode": "RGB",
													"value": {
														"r": 255,
														"g": 0.003891,
														"b": 0.003891
													},
													"alpha": 1
												}
											},
											{
												"offset": 15.9912109375,
												"color": {
													"mode": "RGB",
													"value": {
														"r": 255,
														"g": 255,
														"b": 0
													}
												}
											},
											{
												"offset": 33.0078125,
												"color": {
													"mode": "RGB",
													"value": {
														"r": 0,
														"g": 255,
														"b": 0
													}
												}
											},
											{
												"offset": 51.0009765625,
												"color": {
													"mode": "RGB",
													"value": {
														"r": 0,
														"g": 255,
														"b": 255
													}
												}
											},
											{
												"offset": 66.9921875,
												"color": {
													"mode": "RGB",
													"value": {
														"r": 0,
														"g": 0,
														"b": 255
													}
												}
											},
											{
												"offset": 85.009765625,
												"color": {
													"mode": "RGB",
													"value": {
														"r": 255,
														"g": 0,
														"b": 255
													}
												}
											},
											{
												"offset": 100,
												"color": {
													"mode": "RGB",
													"value": {
														"r": 255,
														"g": 0.003891,
														"b": 0.003891
													},
													"alpha": 1
												}
											}
										]
									},
									"opacity": 0.75,
									"glowTechnique": "softMatte",
									"chokeMatte": 0,
									"blur": 38,
									"shadingNoise": {
										"value": 0,
										"units": "percentUnit"
									},
									"noise": {
										"value": 0,
										"units": "percentUnit"
									},
									"antiAlias": false,
									"innerGlowSource": "edgeGlow",
									"transferSpec": {
										"name": "Half Round"
									},
									"inputRange": {
										"value": 50,
										"units": "percentUnit"
									}
								}
							]
						}
					}
				},
				"filters": [
					{
						"ref": "filter"
					}
				]
			},
			"shape": {
				"type": "rect",
				"x": 150,
				"y": 200,
				"width": 200,
				"height": 200
			},
			"visualBounds": {
				"x": 150,
				"y": 200,
				"width": 200,
				"height": 200
			}
		},
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none"
				},
				"fill": {
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 252.970012,
							"g": 197.757364,
							"b": 137.454736
						},
						"alpha": 1
					}
				},
				"meta": {
					"PS": {
						"fx": {
							"innerGlowMulti": [
								{
									"enabled": true,
									"mode": "darken",
									"color": {
										"mode": "RGB",
										"value": {
											"r": 189.996113,
											"g": 200.708164,
											"b": 255
										},
										"alpha": 1
									},
									"opacity": 0.75,
									"glowTechnique": "softMatte",
									"chokeMatte": 0,
									"blur": 65,
									"shadingNoise": {
										"value": 0,
										"units": "percentUnit"
									},
									"noise": {
										"value": 0,
										"units": "percentUnit"
									},
									"antiAlias": false,
									"innerGlowSource": "edgeGlow",
									"transferSpec": {
										"name": "Linear"
									},
									"inputRange": {
										"value": 50,
										"units": "percentUnit"
									}
								}
							]
						}
					}
				},
				"filters": [
					{
						"ref": "filter-2"
					}
				]
			},
			"shape": {
				"type": "rect",
				"x": 450,
				"y": 200,
				"width": 200,
				"height": 200
			},
			"visualBounds": {
				"x": 450,
				"y": 200,
				"width": 200,
				"height": 200
			}
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {
			"filter": {
				"type": "svgFilter",
				"params": {
					"filterUnits": "userSpaceOnUse",
					"children": [
						{
							"kind": "feGaussianBlur",
							"id": "blur",
							"input": [
								"SourceAlpha"
							],
							"stdDeviation": 12.667
						},
						{
							"kind": "feColorMatrix",
							"id": "color",
							"input": [
								"blur"
							],
							"type": "matrix",
							"values": [
								-1,
								0,
								0,
								0,
								1,
								0,
								-1,
								0,
								0,
								1,
								0,
								0,
								-1,
								0,
								1,
								0,
								0,
								0,
								1,
								0
							]
						},
						{
							"kind": "feColorMatrix",
							"id": "color-2",
							"input": [
								"color"
							],
							"type": "matrix",
							"values": [
								0,
								0,
								0,
								1,
								0,
								0,
								0,
								0,
								1,
								0,
								0,
								0,
								0,
								1,
								0,
								0,
								0,
								0,
								1,
								0
							]
						},
						{
							"kind": "feColorMatrix",
							"id": "color-3",
							"input": [
								"color-2"
							],
							"type": "matrix",
							"values": [
								-1,
								0,
								0,
								0,
								1,
								0,
								-1,
								0,
								0,
								1,
								0,
								0,
								-1,
								0,
								1,
								0,
								0,
								0,
								1,
								0
							]
						},
						{
							"kind": "feComponentTransfer",
							"id": "comp",
							"input": [
								"color-3"
							],
							"color-interpolation-filters": "sRGB",
							"children": [
								{
									"kind": "feFuncR",
									"input": [],
									"type": "table",
									"tableValues": "1 1 1 1 1 1 0.8333 0.6667 0.5 0.3333 0.1667 0 0 0 0 0 0 0 0 0 0 0 0 0.1667 0.3333 0.5 0.6667 0.8333 1 1 1 1 1 1"
								},
								{
									"kind": "feFuncG",
									"input": [],
									"type": "table",
									"tableValues": "0 0.2 0.4 0.6 0.8 1 1 1 1 1 1 1 1 1 1 1 1 1 0.8 0.6 0.4 0.2 0 0 0 0 0 0 0 0 0 0 0 0"
								},
								{
									"kind": "feFuncB",
									"input": [],
									"type": "table",
									"tableValues": "0 0 0 0 0 0 0 0 0 0 0 0 0.1667 0.3333 0.5 0.6667 0.8333 1 1 1 1 1 1 1 1 1 1 1 1 0.8 0.6 0.4 0.2 0"
								}
							]
						},
						{
							"kind": "feComposite",
							"id": "composite",
							"input": [
								"comp",
								"SourceAlpha"
							],
							"operator": "in"
						},
						{
							"kind": "feBlend",
							"id": "blend",
							"input": [
								"composite",
								"SourceGraphic"
							],
							"mode": "lighten"
						}
					],
					"x": 150,
					"y": 200,
					"width": 200,
					"height": 200
				}
			},
			"filter-2": {
				"type": "svgFilter",
				"params": {
					"filterUnits": "userSpaceOnUse",
					"children": [
						{
							"kind": "feGaussianBlur",
							"id": "blur",
							"input": [
								"SourceAlpha"
							],
							"stdDeviation": 21.667
						},
						{
							"kind": "feFlood",
							"id": "flood",
							"input": [],
							"flood-color": {
								"mode": "RGB",
								"value": {
									"r": 189.996113,
									"g": 200.708164,
									"b": 255
								},
								"alpha": 1
							},
							"flood-opacity": 0.75
						},
						{
							"kind": "feComposite",
							"id": "composite-2",
							"input": [
								"flood",
								"blur"
							],
							"operator": "out"
						},
						{
							"kind": "feComposite",
							"id": "composite",
							"input": [
								"composite-2",
								"SourceAlpha"
							],
							"operator": "in"
						},
						{
							"kind": "feBlend",
							"id": "blend",
							"input": [
								"composite",
								"SourceGraphic"
							],
							"mode": "darken"
						}
					],
					"x": 450,
					"y": 200,
					"width": 200,
					"height": 200
				}
			}
		},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 120,
				"altitude": 30
			}
		}
	},
	"version": "1.5.0",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 800,
		"height": 600
	},
	"rasterResolution": 72
}

=== Davidpsj/svgObjectModelGenerator/tests/data/artboards-3/artboards-3-7-om.json
{
	"children": [
		{
			"type": "shape",
			"visible": true,
			"style": {
				"stroke": {
					"type": "none",
					"align": "inside",
					"cap": "butt",
					"join": "miter",
					"width": 13.583333333333332,
					"miterLimit": 100,
					"dash": [],
					"dashOffset": 0,
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 0,
							"b": 0
						},
						"alpha": 1
					},
					"opacity": 1
				},
				"fill": {
					"type": "gradient",
					"gradient": {
						"units": "userSpaceOnUse",
						"x1": 0,
						"y1": 2512,
						"x2": 5924,
						"y2": 2512,
						"ref": "linear-gradient"
					}
				}
			},
			"shape": {
				"type": "path",
				"path": "M4000 2212 C4000 2212 4600 2212 4600 2212 C4600 2212 4600 2812 4600 2812 C4600 2812 4000 2812 4000 2812 C4000 2812 4000 2212 4000 2212Z",
				"winding": "evenodd"
			},
			"visualBounds": {
				"x": 4000,
				"y": 2212,
				"width": 600,
				"height": 600
			}
		}
	],
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {
			"linear-gradient": {
				"stops": [
					{
						"offset": 0,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 249,
								"g": 229.99611,
								"b": 0
							},
							"alpha": 1
						}
					},
					{
						"offset": 0.050048828125,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 249,
								"g": 229.99611,
								"b": 0
							}
						}
					},
					{
						"offset": 0.35009765625,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 111.003892,
								"g": 21.003892,
								"b": 108.000001
							}
						}
					},
					{
						"offset": 0.64990234375,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 253,
								"g": 124,
								"b": 0
							}
						}
					},
					{
						"offset": 0.949951171875,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 0,
								"g": 40.000001,
								"b": 116.000001
							}
						}
					},
					{
						"offset": 1,
						"color": {
							"mode": "RGB",
							"value": {
								"r": 0,
								"g": 40.000001,
								"b": 116.000001
							},
							"alpha": 1
						}
					}
				],
				"type": "linear"
			}
		},
		"masks": {},
		"patterns": {}
	},
	"artboards": {},
	"meta": {
		"PS": {
			"globalLight": {
				"angle": 90,
				"altitude": 30
			}
		}
	},
	"version": "1.0.0",
	"name": "Untitled-1",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 5924,
		"height": 5024
	},
	"rasterResolution": 326
}

=== Davidpsj/svgObjectModelGenerator/tests/data/group-2-om.json
{
	"children": [
		{
			"type": "group",
			"visible": true,
			"style": {
				"opacity": 0.35,
				"isolation": "isolate",
				"blendMode": "multiply",
				"stroke": {
					"type": "none"
				}
			},
			"name": "Group",
			"group": {
				"children": [
					{
						"type": "shape",
						"visible": true,
						"style": {
							"stroke": {
								"type": "solid",
								"align": "inside",
								"cap": "butt",
								"join": "miter",
								"width": 3,
								"dash": [],
								"dashOffset": 0,
								"color": {
									"mode": "RGB",
									"value": {
										"r": 241.881842,
										"g": 101.179413,
										"b": 33.72992
									},
									"alpha": 1
								},
								"opacity": 1,
								"miterLimit": 100
							},
							"fill": {
								"type": "solid",
								"color": {
									"mode": "RGB",
									"value": {
										"r": 43.785993,
										"g": 207.000003,
										"b": 38.155641
									},
									"alpha": 1
								}
							}
						},
						"visualBounds": {
							"x": 100,
							"y": 100,
							"width": 200,
							"height": 200
						},
						"shape": {
							"type": "rect",
							"x": 100,
							"y": 100,
							"width": 200,
							"height": 200
						}
					}
				]
			}
		}
	],
	"artboards": {},
	"version": "0.1.0",
	"name": "group.psd",
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 800,
		"height": 600
	},
	"resources": {
		"clipPaths": {},
		"filters": {},
		"gradients": {},
		"masks": {},
		"patterns": {}
	},
	"rasterResolution": 72
}

=== Davidpsj/svgObjectModelGenerator/tests/data/responsive/responsive-om.json
{
	"name": "generatedAsset",
	"version": "1.5.0",
	"children": [
		{
			"type": "shape",
			"shape": {
				"type": "ellipse",
				"cx": 105,
				"cy": 155,
				"ry": 150,
				"rx": 100
			},
			"style": {
				"stroke": {
					"width": 10,
					"type": "solid",
					"color": {
						"mode": "RGB",
						"value": {
							"r": 0,
							"g": 127,
							"b": 0
						}
					}
				}
			},
			"visualBounds": {
				"x": 0,
				"y": 0,
				"width": 310,
				"height": 210
			}
		}
	],
	"viewSource": {
		"x": 0,
		"y": 0,
		"width": 400,
		"height": 400
	},
	"resources": {}
}
